tasks:
  - name: "预约挂号_task_000"
    description: "预约挂号，挂一个天津孟召伟主任医师的号"
    max_steps: 50
    enabled: true

  - name: "预约挂号_task_001"
    description: "预约挂号，挂北京大学人民医院的妇科号"
    max_steps: 50
    enabled: true

  - name: "预约挂号_task_002"
    description: "预约挂号，挂一个中日友好医院的皮肤美容科的号"
    max_steps: 50
    enabled: true

  - name: "预约挂号_task_003"
    description: "预约挂号，挂一个天津医院的全科的号"
    max_steps: 50
    enabled: true

  - name: "预约挂号_task_004"
    description: "预约挂号，挂一个北京，职业病科的号"
    max_steps: 50
    enabled: true

  - name: "预约挂号_task_005"
    description: "预约挂号，挂一个天津第一中心医院的营养科的最早的号"
    max_steps: 50
    enabled: true

  - name: "预约挂号_task_006"
    description: "预约挂号，挂一个天津和平区，外科的号"
    max_steps: 50
    enabled: true

  - name: "预约挂号_task_007"
    description: "预约挂号，挂一个中医学科的号"
    max_steps: 50
    enabled: true

  - name: "预约挂号_task_008"
    description: "预约挂号，挂一个山西，康复医学科的这周日的号"
    max_steps: 50
    enabled: true

  - name: "预约挂号_task_009"
    description: "预约挂号，挂一个辽宁，失眠疾病，这周六的号"
    max_steps: 50
    enabled: true


  - name: "预约挂号_task_010"
    description: "预约挂号，挂一个上海瑞金医院的内分泌科的号"
    max_steps: 50
    enabled: true

  - name: "预约挂号_task_011"
    description: "预约挂号，挂一个北京协和医院的心内科的号"
    max_steps: 50
    enabled: true

  - name: "预约挂号_task_012"
    description: "预约挂号，挂一个广州，儿科的最早的号"
    max_steps: 50
    enabled: true

  - name: "预约挂号_task_013"
    description: "预约挂号，挂一个复旦大学附属中山医院的消化内科的号"
    max_steps: 50
    enabled: true

  - name: "预约挂号_task_014"
    description: "预约挂号，挂一个天津肿瘤医院的肿瘤外科的号"
    max_steps: 50
    enabled: true

  - name: "预约挂号_task_015"
    description: "预约挂号，挂一个北京，眼科的这周五的号"
    max_steps: 50
    enabled: true

  - name: "预约挂号_task_016"
    description: "预约挂号，挂一个浙江大学医学院附属第一医院的骨科的号"
    max_steps: 50
    enabled: true

  - name: "预约挂号_task_017"
    description: "预约挂号，挂一个成都，口腔科的明天的号"
    max_steps: 50
    enabled: true

  - name: "预约挂号_task_018"
    description: "预约挂号，挂一个湖南湘雅医院的神经内科的最早的号"
    max_steps: 50
    enabled: true

  - name: "预约挂号_task_019"
    description: "预约挂号，挂一个南京鼓楼医院的泌尿外科的这周三的号"
    max_steps: 50
    enabled: true


default_task: 0
